### ISSUE TITLE
I install kindling, but agent start failed.

### ISSUE THREAD

**Issue by shengjiangfeng** [harmonycloud/kindling#646]
The kindling agent got this error :  kindling probe init err: error opening device /host/dev/kindling-falcolib0. Make sure you have root credentials and that the kindling-falcolib-probe module is loaded. Please read the FAQ on our website for trouble-shooting this.2024/09/09 02:39:30 Failed to run application: failed to start application: fail to init probe.
Can u help me solve this error?

**Comment by dxsup** [comment]
Read this: http://kindling.harmonycloud.cn/docs/installation/faq/#error-precompiled-module-at-optkindling-is-not-found

**Comment by shengjiangfeng** [comment]
Thanks a lot.
